version: "3.8"
services: 
    postgres:
        build: ./database/
        environment:
            POSTGRES_PASSWORD: password
        ports: 
            - "5432:5432"
    redis:
        image: redis
        ports:
            - "6379:6379"