
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.0
  serverless: circleci/serverless-framework@1.0.1

jobs:
  build-and-test:
    docker:
      - image: 'cimg/node:16.1.0'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd ./site && npm install
      - run:
          name: Install Codecov
          command: sudo npm install -g codecov
      - run: 
          name: Test
          command: cd ./site && npm run test
      - run:
          name: Report Coverage
          command: cd ./site && npm run report-coverage
  deploy-dev:
    executor: serverless/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd ./site && npm install
      - aws-cli/setup
      - serverless/setup:
          app-name: pf-web
          org-name: ryanallen
      - run:
          name: deploy
          command: cd ./site && serverless deploy --stage dev
  deploy-prod:
    executor: serverless/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd ./site && npm install
      - aws-cli/setup
      - serverless/setup:
          app-name: pf-web
          org-name: ryanallen
      - run:
          name: deploy
          command: cd ./site && serverless deploy --stage prod

workflows:
  version: 2
  build-deploy:
    jobs:
      # - build-and-test
      - deploy-dev:
          context: 
            - pf-web
            - pf-web-dev
          # requires:
            # - build-and-test
          filters:
            branches:
              only:
                - develop
                - /feature\/.*/
      - deploy-prod:
          context: 
            - pf-web
            - pf-web-prod
          # requires:
          #   - build-and-test
          filters:
            branches:
              only:
                - master