component: aws-dynamodb

name: pf-web-sessionstore

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

inputs:
  name: ${name}-${stage}
  region: us-east-1
  attributeDefinitions:
    - AttributeName: sessionKey
      AttributeType: S
  keySchema:
    - AttributeName: sessionKey
      KeyType: HASH