component: aws-dynamodb

name: pf-club-database

inputs:
  name: ${name}-${stage}
  region: us-east-1
  deletionPolicy: delete
  attributeDefinitions:
    - AttributeName: id
      AttributeType: S
  keySchema:
    - AttributeName: id
      KeyType: HASH

